StreemServise/StreemServise/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('music_app.urls', 'music_app'), namespace='music_app')),
    path('admin/', admin.site.urls),
]

StreemServise/music_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_mame = 'music_app'

urlpatterns = [
    # path('album/<album.id>/', views.single_music_page, name='album'),
    path('album/<int:pk>/', views.single_music_page, name='album'),
    path('', views.music_list_page, name='home'),

]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

StreemServise/music_app/models.py
from django.db import models
from django.core.validators import FileExtensionValidator


class SongWriter(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='song_writer_image/%Y/%m/%d/',
                              blank=True,
                              null=True)

    def __str__(self):
        return self.name


class Song(models.Model):
    song_title = models.CharField(max_length=100)
    song_writer = models.ForeignKey(SongWriter,
                                    on_delete=models.CASCADE,
                                    related_name='songs',
                                    verbose_name='songwriter')
    file = models.FileField(
        upload_to='music/%Y/%m/%d/',
        validators=[FileExtensionValidator(allowed_extensions=['mp3'])]
    )

    def __str__(self):
        return self.song_title


class Album(models.Model):
    album_title = models.CharField(max_length=100)
    song_writer = models.ForeignKey(SongWriter,
                                    related_name='albums',
                                    on_delete=models.CASCADE)

    image = models.ImageField(upload_to='song_image/%Y/%m/%d/')
    release_date = models.DateTimeField(auto_now_add=True)
    songs = models.ManyToManyField(Song, related_name='albums')
    slug = models.SlugField(max_length=25, unique=True)

    def __str__(self):
        return self.album_title

    class Meta:
        ordering = ['-release_date']

StreemServise/music_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import StreamingHttpResponse

from .models import Song, Album, SongWriter


def music_list_page(request):
    albums = Album.objects.all()
    context = {
        'albums': albums,
    }
    template_name = 'music_app/home.html'
    return render(request, template_name, context)


# def music_list_page(request, album_id):
#     albums = Album.objects.get(id=album_id)
#     context = {
#         'albums': albums,
#     }
#     template_name = 'music_app/home.html'
#     return render(request, template_name, context)


def single_music_page(request, pk):
    song = get_object_or_404(Song, id=pk)
    album = song.albums.last()
    template_name = 'music_app/music_page.html'
    context = {
        'song': song,
        'album': album,
    }
    return render(request, template_name, context)

StreemServise/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image ">
  <link rel="apple-touch-icon" sizes="180x180"
        href="{% static 'img/fav/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32"
        href="{% static 'img/fav/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16"
        href="{% static 'img/fav/favicon-16x16.png' %}">
  <meta name="msapplication-TileColor" content="#000">
  <meta name="theme-color" content="#ffffff">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'
        type='text/css'>


  <title>
    {% block title %}
    All Albums
    {% endblock %}
  </title>
</head>


<body>
{% include 'includes/header.html' %}

<main>
  <div class="container py-5">
    {% block content %}


    {% endblock %}
  </div>
</main>
</body>
</html>

StreemServise/templates/includes/header.html
{% load static %}

<header class="p-3 bg-dark text-white">
  <div class="container">

    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li>
          <a href="/" class="nav-link px-2 text-white">
            Home
          </a>
        </li>
    </div>
  </div>
</header>

StreemServise/templates/music_app/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<div class="row row-cols-1 row-cols-md-3 g-4">


{% for album in albums %}


{% include 'music_app/includes/single_post.html' %}


{% endfor %}



</div>

{% endblock %}

StreemServise/templates/music_app/includes/single_post.html
<div class="col">
  <div class="card h-100; shadow" style="border-radius: 12px;">
    <img src="{{ album.image.url }}"
         class="card-img-top" alt=""/>
    <div class="card-body">
      <h5 class="card-title">
        <a href="{% url 'music_app:album' album.slug %}">
        {{ album.album_title }}
        </a>
      </h5>
      <p class="card-text">
        {{ album.song_writer }}
      </p>
    </div>
  </div>
</div>

StreemServise/templates/music_app/music_page.html
{% extends 'base.html' %}

{% load thumbnail %}
{% load static %}


{% block title %}
{{ song.song_writer }} - {{ song.song_title }}
{% endblock %}




{% block content %}

<head>
  <link rel="stylesheet" href="{% static 'css/pleer_style.css' %}">
</head>

<div class="container">
  <head_up>
    <div class="playlist">
      <a href="/">
        <i class="fa fa-bars"></i>
      </a>
    </div>
  </head_up>

  <main>


    <div class="album-art">
      <img src="{{ album.image.url }}"/>

    </div>

    <div style="height: 200px; overflow: auto; display: inline-block; direction: rtl; text-align: left;"
         class="bar">
      {% for single in songs_in_cur_album %}
      <ul style="color: white">{{ single.song_writer }} - {{single.song_title|safe|truncatechars:20 }}
      </ul>
      {% endfor %}
    </div>


    <div class="player">
      <i class="fa fa-repeat"></i>
      <i class="fa fa-fast-backward"></i>

      <i class="fa fa-play" id="play-pause-btn"></i>
      <i class="fa fa-fast-forward"></i>
      <i class="fa fa-random"></i>


    </div>

  </main>
  <foot>
    <div class="title">{{ song.song_writer }} - {{ song.song_title }}
    </div>
    <div class="time-tracker">
      <div class="timer">
        <div class="bg">
        </div>
      </div>

      <div class="time">00:00</div>
    </div>
    <div class="volume-control">
      <i class="fa fa-volume-up"></i>
      <input type="range" class="slider" min="0" max="1" step="0.01" value="1"
             id="volume-slider" orient="vertical">
    </div>
  </foot>
  <audio id="audio">
    <source src="{{ song.file.url }}" type="audio/mpeg">
  </audio>
</div>

<script>

const audio = document.getElementById('audio');
const playPauseBtn = document.getElementById('play-pause-btn');
const bg = document.querySelector('.bg');
const timeEl = document.querySelector('.time');
const volumeSlider = document.getElementById('volume-slider');

bg.addEventListener('click', function(e) {
  const { offsetX } = e;
  const { offsetWidth } = this;
  const progress = offsetX / offsetWidth;
  audio.currentTime = audio.duration * progress;
});

audio.addEventListener('timeupdate', function() {
  const { currentTime, duration } = this;
  const progress = (currentTime / duration) * 100;
  bg.style.width = `${progress}%`;

  const minutes = Math.floor(currentTime / 60);
  const seconds = Math.floor(currentTime % 60);
  timeEl.textContent = `${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
});

playPauseBtn.addEventListener('click', () => {
  if (audio.paused) {
    audio.play();
    playPauseBtn.textContent = 'Pausa';
  } else {
    audio.pause();
    playPauseBtn.textContent = 'Play';
  }
});

audio.addEventListener('loadedmetadata', () => {
  const minutes = Math.floor(audio.duration / 60);
  const seconds = Math.floor(audio.duration % 60);
  timeEl.textContent = `${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
});

volumeSlider.addEventListener('input', () => {
  audio.volume = volumeSlider.value;
});





</script>

{% endblock %}